export const AUTH_ON_LOAD_LOGIN = "AUTH_ON_LOAD_LOGIN";
export const AUTH_USER_LOGGED_IN = "AUTH_USER_LOGGED_IN";
export const AUTH_USER_LOGGED_OUT = "AUTH_USER_LOGGED_OUT";
export const AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND";
export const AUTH_TOKEN_IN_VALID = "AUTH_TOKEN_IN_VALID";
